# Generated by Django 3.2.5 on 2021-08-13 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=100)),
                ('video_url', models.URLField(blank=True, default='', max_length=10000000000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='videos/Thumb/')),
            ],
        ),
    ]
