# Generated by Django 3.2.5 on 2021-07-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmineApp', '0004_auto_20210714_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
