# Generated by Django 3.2.5 on 2021-07-14 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AmineApp', '0006_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='Videos/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
