# Generated by Django 3.2.5 on 2021-07-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmineApp', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='', upload_to='VideosImg/'),
        ),
    ]
