# Generated by Django 3.2.5 on 2021-07-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmineApp', '0008_alter_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Video',
            field=models.FileField(default=True, upload_to='Videos/'),
        ),
    ]
