# Generated by Django 3.2.5 on 2021-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmineApp', '0009_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='videos/Thumb/'),
        ),
    ]
